---

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes 
    name: docker-ce 
    state: latest

- name: Install python-pip
  apt:
    name: python-pip
    state: latest

- name: Pip install docker-py
  pip:
    name: docker-py
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
 
- name: Add user psapp to docker group
  user:
    name: psapp
    groups: docker
    append: yes